# Generated by Django 5.2 on 2025-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_billing_file_alter_labreport_is_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='file',
        ),
        migrations.AddField(
            model_name='labreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
